  [build]
  command = "npm run build"
  publish = "dist"                
  functions = "backend/functions"  

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/data/projects.json"]  

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200