[build]
  command = "npm run build"
  publish = "dist"                
  functions = "backend/functions" 

[functions]  
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/backend/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200